services:
  app:
    build:
      context: .
      dockerfile: Docker/dockerfile/app.Dockerfile.dev
    container_name: sipta-app-dev
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    depends_on:
      - cache
      - database
    ports:
      - "8000:8000"
    networks:
      - sipta-dev

  cache:
    image: redis:alpine
    container_name: cache-dev
    restart: unless-stopped
    networks:
      - sipta-dev

  database:
    image: mysql:8.0
    container_name: sipta-db-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sipta-dev

networks:
  sipta-dev:
    driver: bridge

volumes:
  db-data:
